{{- if .Values.imageCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.imageCredentials.name }}
  name: {{ .Values.imageCredentials.name }}
  {{- else}}
  name: "{{ .Chart.Name }}-registry-secret"
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}